/**
 * Display helper mapping country names and ISO 3166-1 alpha-2 codes to Unicode flag emojis.
 *
 * Covers all 275 country labels published in the Charity Commission register
 * (data/register.sqlite), plus common international aliases and ISO codes.
 */

/** Converts a 2-letter ISO 3166-1 alpha-2 code to its regional indicator flag emoji. */
export function isoToFlagEmoji(iso: string | null | undefined): string | null {
  if (!iso) return null;
  const trimmed = iso.trim().toUpperCase();
  if (trimmed.length !== 2) return null;
  const first = trimmed.charCodeAt(0);
  const second = trimmed.charCodeAt(1);
  if (first < 65 || first > 90 || second < 65 || second > 90) return null;
  return String.fromCodePoint(0x1f1e6 + first - 65, 0x1f1e6 + second - 65);
}

/** Special subdivision / non-standard flags. */
const SPECIAL_FLAGS: Record<string, string> = {
  scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  england: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
};

/**
 * Complete normalized mapping from Charity Commission country names (and aliases)
 * to ISO 3166-1 alpha-2 country codes.
 */
const COUNTRY_TO_ISO: Record<string, string> = {
  "abu dhabi": "AE",
  afghanistan: "AF",
  ajman: "AE",
  akrotiri: "CY",
  "aland islands": "AX",
  albania: "AL",
  algeria: "DZ",
  "american samoa": "AS",
  andorra: "AD",
  angola: "AO",
  anguilla: "AI",
  antarctica: "AQ",
  "antigua and barbuda": "AG",
  argentina: "AR",
  armenia: "AM",
  aruba: "AW",
  ascension: "AC",
  australia: "AU",
  austria: "AT",
  azerbaijan: "AZ",
  bahamas: "BS",
  bahrain: "BH",
  "baker island": "UM",
  bangladesh: "BD",
  barbados: "BB",
  belarus: "BY",
  belgium: "BE",
  belize: "BZ",
  benin: "BJ",
  bermuda: "BM",
  bhutan: "BT",
  bolivia: "BO",
  bonaire: "BQ",
  "bosnia and herzegovina": "BA",
  botswana: "BW",
  "bouvet island": "BV",
  brazil: "BR",
  "british antarctic territory": "AQ",
  "british indian ocean territory": "IO",
  "british virgin islands": "VG",
  brunei: "BN",
  bulgaria: "BG",
  "burkina faso": "BF",
  burma: "MM",
  burundi: "BI",
  cambodia: "KH",
  cameroon: "CM",
  canada: "CA",
  "cape verde": "CV",
  "cayman islands": "KY",
  "central african republic": "CF",
  ceuta: "ES",
  chad: "TD",
  chile: "CL",
  china: "CN",
  "christmas island": "CX",
  "cocos (keeling) islands": "CC",
  colombia: "CO",
  comoros: "KM",
  congo: "CG",
  "congo (democratic republic)": "CD",
  "democratic republic of the congo": "CD",
  "dr congo": "CD",
  "drc": "CD",
  "cook islands": "CK",
  "costa rica": "CR",
  croatia: "HR",
  cuba: "CU",
  cyprus: "CY",
  "czech republic": "CZ",
  czechia: "CZ",
  denmark: "DK",
  dhekelia: "CY",
  djibouti: "DJ",
  dominica: "DM",
  "dominican republic": "DO",
  dubai: "AE",
  "east timor": "TL",
  "timor-leste": "TL",
  "easter island": "CL",
  ecuador: "EC",
  egypt: "EG",
  "el salvador": "SV",
  "equatorial guinea": "GQ",
  eritrea: "ER",
  estonia: "EE",
  eswatini: "SZ",
  swaziland: "SZ",
  ethiopia: "ET",
  "falkland islands": "FK",
  "faroe islands": "FO",
  fiji: "FJ",
  finland: "FI",
  france: "FR",
  "french guiana": "GF",
  "french polynesia": "PF",
  "french southern territories": "TF",
  fujairah: "AE",
  gabon: "GA",
  gambia: "GM",
  georgia: "GE",
  germany: "DE",
  ghana: "GH",
  gibraltar: "GI",
  greece: "GR",
  greenland: "GL",
  grenada: "GD",
  guadeloupe: "GP",
  guam: "GU",
  guatemala: "GT",
  guernsey: "GG",
  guinea: "GN",
  "guinea-bissau": "GW",
  guyana: "GY",
  haiti: "HT",
  "heard island and mcdonald islands": "HM",
  honduras: "HN",
  "hong kong": "HK",
  "howland island": "UM",
  hungary: "HU",
  iceland: "IS",
  india: "IN",
  indonesia: "ID",
  iran: "IR",
  iraq: "IQ",
  ireland: "IE",
  "isle of man": "IM",
  israel: "IL",
  italy: "IT",
  "ivory coast": "CI",
  "côte d'ivoire": "CI",
  jamaica: "JM",
  japan: "JP",
  "jarvis island": "UM",
  jersey: "JE",
  "johnston atoll": "UM",
  jordan: "JO",
  kazakhstan: "KZ",
  kenya: "KE",
  "kingman reef": "UM",
  kiribati: "KI",
  kosovo: "XK",
  kuwait: "KW",
  kyrgyzstan: "KG",
  laos: "LA",
  latvia: "LV",
  lebanon: "LB",
  lesotho: "LS",
  liberia: "LR",
  libya: "LY",
  liechtenstein: "LI",
  lithuania: "LT",
  luxembourg: "LU",
  macau: "MO",
  macedonia: "MK",
  "north macedonia": "MK",
  madagascar: "MG",
  malawi: "MW",
  malaysia: "MY",
  maldives: "MV",
  mali: "ML",
  malta: "MT",
  "marshall islands": "MH",
  martinique: "MQ",
  mauritania: "MR",
  mauritius: "MU",
  mayotte: "YT",
  melilla: "ES",
  mexico: "MX",
  micronesia: "FM",
  "midway islands": "UM",
  moldova: "MD",
  monaco: "MC",
  mongolia: "MN",
  montenegro: "ME",
  montserrat: "MS",
  morocco: "MA",
  mozambique: "MZ",
  myanmar: "MM",
  namibia: "NA",
  nauru: "NR",
  "navassa island": "UM",
  nepal: "NP",
  netherlands: "NL",
  "netherlands antilles": "CW",
  "new caledonia": "NC",
  "new zealand": "NZ",
  nicaragua: "NI",
  niger: "NE",
  nigeria: "NG",
  niue: "NU",
  "norfolk island": "NF",
  "north korea": "KP",
  "northern ireland": "GB",
  "northern mariana islands": "MP",
  norway: "NO",
  "occupied palestinian territories": "PS",
  palestine: "PS",
  oman: "OM",
  pakistan: "PK",
  palau: "PW",
  "palmyra atoll": "UM",
  panama: "PA",
  "papua new guinea": "PG",
  paraguay: "PY",
  peru: "PE",
  philippines: "PH",
  "pitcairn, henderson, ducie and oeno islands": "PN",
  pitcairn: "PN",
  poland: "PL",
  portugal: "PT",
  "puerto rico": "PR",
  qatar: "QA",
  "ras al-khaimah": "AE",
  romania: "RO",
  russia: "RU",
  rwanda: "RW",
  réunion: "RE",
  reunion: "RE",
  saba: "BQ",
  "saint barthélemy": "BL",
  "saint barthelemy": "BL",
  "saint helena": "SH",
  "saint pierre and miquelon": "PM",
  "saint vincent": "VC",
  "saint vincent and the grenadines": "VC",
  "saint-martin": "MF",
  samoa: "WS",
  "san marino": "SM",
  "saudi arabia": "SA",
  scotland: "GB",
  senegal: "SN",
  serbia: "RS",
  seychelles: "SC",
  "sierra leone": "SL",
  singapore: "SG",
  "sint eustatius": "BQ",
  "sint maarten": "SX",
  slovakia: "SK",
  slovenia: "SI",
  "solomon islands": "SB",
  somalia: "SO",
  "south africa": "ZA",
  "south georgia and south sandwich islands": "GS",
  "south korea": "KR",
  "south sudan": "SS",
  spain: "ES",
  "sri lanka": "LK",
  "st kitts and nevis": "KN",
  "st lucia": "LC",
  sudan: "SD",
  suriname: "SR",
  "svalbard and jan mayen": "SJ",
  sweden: "SE",
  switzerland: "CH",
  syria: "SY",
  "são tomé and principe": "ST",
  "sao tome and principe": "ST",
  taiwan: "TW",
  tajikistan: "TJ",
  tanzania: "TZ",
  thailand: "TH",
  "the bahamas": "BS",
  "the gambia": "GM",
  togo: "TG",
  tokelau: "TK",
  tonga: "TO",
  "trinidad and tobago": "TT",
  "tristan da cunha": "TA",
  tunisia: "TN",
  turkey: "TR",
  türkiye: "TR",
  turkmenistan: "TM",
  "turks and caicos islands": "TC",
  tuvalu: "TV",
  uganda: "UG",
  ukraine: "UA",
  "umm al-quwain": "AE",
  "united arab emirates": "AE",
  uae: "AE",
  "united kingdom": "GB",
  uk: "GB",
  "united states": "US",
  "united states of america": "US",
  usa: "US",
  "united states virgin islands": "VI",
  uruguay: "UY",
  uzbekistan: "UZ",
  vanuatu: "VU",
  "vatican city": "VA",
  venezuela: "VE",
  vietnam: "VN",
  "wake island": "UM",
  "wallis and futuna": "WF",
  "western sahara": "EH",
  yemen: "YE",
  zambia: "ZM",
  zimbabwe: "ZW",
};

/**
 * Returns the ISO 3166-1 alpha-2 code for a country name if recognized.
 */
export function countryToIso(country: string | null | undefined): string | null {
  if (!country) return null;
  const normalized = country.trim().toLowerCase();
  if (normalized.length === 2) return normalized.toUpperCase();
  return COUNTRY_TO_ISO[normalized] ?? null;
}

/**
 * Returns the Unicode flag emoji for a given country name or 2-letter ISO code.
 * Returns null if unrecognised.
 *
 * Examples:
 *   countryFlagEmoji("Kenya") -> "🇰🇪"
 *   countryFlagEmoji("Occupied Palestinian Territories") -> "🇵🇸"
 *   countryFlagEmoji("Congo (Democratic Republic)") -> "🇨🇩"
 *   countryFlagEmoji("Burma") -> "🇲🇲"
 *   countryFlagEmoji("Scotland") -> "🏴󠁧󠁢󠁳󠁣󠁴󠁿"
 */
export function countryFlagEmoji(country: string | null | undefined): string | null {
  if (!country) return null;
  const normalized = country.trim().toLowerCase();

  const special = SPECIAL_FLAGS[normalized];
  if (special) return special;

  // Direct 2-letter code check
  if (normalized.length === 2) {
    return isoToFlagEmoji(normalized);
  }

  const iso = COUNTRY_TO_ISO[normalized];
  if (iso) {
    return isoToFlagEmoji(iso);
  }

  return null;
}
