import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    // Generated by the local Supabase/Docker stack. It contains bundled edge-runtime
    // code that is not authored or maintained by this repository.
    "supabase/.temp/**",
    "next-env.d.ts",
    // Vendored verbatim by `shadcn add @animate-ui/...`. Upstream source, not
    // authored here — re-running the CLI would overwrite any local fixes, so it
    // is exempt from the react-compiler rules rather than patched.
    "src/components/animate-ui/**",
    "src/hooks/use-is-in-view.tsx",
  ]),
  {
    // `src/lib/supabase/admin-client-factory.ts` holds the service-role key and
    // deliberately carries no `server-only` guard, because the F038 ingestion
    // runner executes outside Next.js and `server-only` throws there. That makes
    // it the one way to obtain an RLS-bypassing client without tripping the guard,
    // so importing it is restricted to the places that legitimately need it.
    // Everything else goes through `admin.ts`, which keeps the guard.
    files: ["src/**/*.{ts,tsx}"],
    ignores: [
      "src/lib/supabase/admin.ts",
      "src/lib/ingestion/**/*.{ts,tsx}",
      // F041: promotePendingCharityCommissionRecords runs the same way as the
      // ingestion runner — a plain node script (scripts/run-standardize-charity-
      // commission.mts), so it can't import admin.ts either.
      "src/lib/standardize/**/*.{ts,tsx}",
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/supabase/admin-client-factory"],
              message:
                "Import createAdminClient from src/lib/supabase/admin.ts instead — it keeps the `server-only` guard. admin-client-factory.ts is reserved for admin.ts and the F038 ingestion runner, which runs outside Next.js.",
            },
          ],
        },
      ],
    },
  },
]);

export default eslintConfig;
