-- Rollback of 20260911090000_add_score_factors_to_latest_scores.sql (F095).
--
-- Safe: the column is derived, reproducible scoring data. Dropping it loses
-- nothing that cannot be regenerated by the next `npm run backfill:scores`
-- once the column returns.

alter table public.latest_scores
  drop constraint if exists latest_scores_score_factors_shape;

alter table public.latest_scores
  drop column if exists score_factors;
