-- Rollback for: 20260828000000_version_client_booklets.sql
-- Apply manually against the target DB to reverse the paired migration.
--
-- Restores the single-row-per-organisation shape: the UNIQUE constraint, the
-- updated_at column and its trigger, and the UPDATE policy/grant. Safe only
-- before any real regeneration history has been written under the versioned
-- shape — if more than one row exists for an organisation, adding the UNIQUE
-- constraint back will fail, and there is no correct automatic choice of which
-- row to keep. Resolve that by hand (decide which version survives) before
-- running this against any environment with real data.

alter table public.client_booklets
  add column updated_at timestamptz not null default now();

create trigger client_booklets_set_updated_at
  before update on public.client_booklets
  for each row execute function public.set_updated_at();

drop index public.client_booklets_organisation_idx;

alter table public.client_booklets
  add constraint client_booklets_organisation_id_key unique (organisation_id);

grant update on public.client_booklets to authenticated;

create policy client_booklets_update_can_contact on public.client_booklets
  for update to authenticated
  using (app.is_active_user() and app.can_contact_organisation(organisation_id))
  with check (app.is_active_user() and app.can_contact_organisation(organisation_id));

comment on table public.client_booklets is
  'The most recently generated booklet per client (F085), so a CAM reopening a client '
  'sees it immediately instead of triggering a new Gemini call. Upsert target keyed on '
  'organisation_id, not a history.';
comment on column public.client_booklets.generated_at is
  'When this saved version was generated by Gemini. Distinct from updated_at (last row '
  'touch) in case a future non-generation edit is ever added; today they always match.';
