-- Migration: create_client_booklets
-- Story: F085 (#349) Save Generated Booklet, on top of F082 (#85) Generate Client
--   Booklet and F084 (#348) Use Website URL in Booklet.
-- Spec: docs/rls-permission-matrix.md §3.2-style shared-read pattern (added below);
--   read/write predicates reuse app.is_active_user() / app.can_contact_organisation()
--   from create_rls_helpers (20260722103200), matching the client:contact gate the
--   /api/clients/[id]/booklet route already enforces at the application layer.
--
-- ONE ROW PER ORGANISATION, NOT A HISTORY:
--   F085's own ACs describe a single "current" saved booklet a CAM sees immediately on
--   reopening a client, plus when it was generated (AC1-AC3) — not a version history.
--   F085's ticket flags "Storage format/versioning" as an open question; F112 (Save AI
--   Prompt and Output) is the separate ticket that would own a full generation-history
--   audit trail, and it is out of scope here the same way it was deferred out of F082
--   (see build-prompt.ts's own header). So this is an upsert target keyed on
--   organisation_id, not an append-only log like ENRICHMENT_RESULTS — regenerating
--   replaces the saved row rather than adding to it.
--
-- SCHEMA CHANGE APPROVAL RECORD — DEVIATION, NOT YET MIRRORED (SOP §7):
--   This table does not exist in the Data Model spreadsheet yet (tab 04/02). F082 and
--   F084 shipped generate-and-display only, with no persistence, so there was nothing
--   to model until now. Flagging for Bashir to add CLIENT_BOOKLETS to tab 04 and its
--   columns to tab 02 — same kind of gap as NOTES.author_id (20260804180000) — rather
--   than blocking F085 on a spreadsheet edit this repo cannot make. Himanshu owns F085
--   and this storage shape per his own call.
--   Change        | Add CLIENT_BOOKLETS (new table)
--   Reason        | F085: persist a generated booklet so reopening a client doesn't
--                 | re-bill Gemini for the same content.
--   Compatibility | New table. Nothing existing reads or writes it.
--   Data migration| None.
--   Security      | RLS on, policies in this migration. Shared read (client:view, same
--                 | as NOTES/ENRICHMENT_RESULTS); write/upsert requires
--                 | app.can_contact_organisation() (client:contact), matching the
--                 | booklet route's own permission gate.
--   Documentation | Not yet in the Data Model spreadsheet — flagged above.
--
-- Reversibility: paired rollback in ../rollback/20260827000000_create_client_booklets.down.sql

create table public.client_booklets (
  id                    uuid primary key default gen_random_uuid(),
  -- One saved booklet per client — see header. A second generation for the same
  -- organisation upserts this row rather than inserting a new one.
  organisation_id       uuid not null unique references public.organisations (id) on delete cascade,
  booklet_text          text not null,
  -- F084 context, kept alongside the text so a CAM (or a future regenerate) can see
  -- what informed this specific saved version — not a live/authoritative field, just
  -- what was true at generation time.
  website_url           text,
  website_context_used  boolean not null default false,
  generated_at          timestamptz not null default now(),
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),

  constraint client_booklets_text_not_blank check (length(trim(booklet_text)) > 0)
);

comment on table public.client_booklets is
  'The most recently generated booklet per client (F085), so a CAM reopening a client '
  'sees it immediately instead of triggering a new Gemini call. Upsert target keyed on '
  'organisation_id, not a history — see this migration''s header for why.';
comment on column public.client_booklets.generated_at is
  'When this saved version was generated by Gemini. Distinct from updated_at (last row '
  'touch) in case a future non-generation edit is ever added; today they always match.';

create trigger client_booklets_set_updated_at
  before update on public.client_booklets
  for each row execute function public.set_updated_at();


-- ---------------------------------------------------------------------------
-- Security. REVOKE before GRANT (matrix §2.1) — see create_org_children for why this
-- order matters on a fresh Supabase-managed public table.
-- ---------------------------------------------------------------------------
revoke all on public.client_booklets from anon, authenticated;

alter table public.client_booklets enable row level security;

-- Shared read, same as NOTES/ENRICHMENT_RESULTS: F019 makes client context visible to
-- every active user regardless of role, including viewer (client:view).
grant select on public.client_booklets to authenticated;

create policy client_booklets_select_active on public.client_booklets
  for select to authenticated using (app.is_active_user());

-- Insert/update (the upsert path) requires the same client:contact predicate the
-- booklet route already checks at the application layer — admin, or a CAM who owns
-- the organisation or where it's unowned. Delete is admin-only, matching
-- ENRICHMENT_RESULTS: a bad saved booklet is an admin cleanup, not a CAM action.
grant insert, update, delete on public.client_booklets to authenticated;

create policy client_booklets_insert_can_contact on public.client_booklets
  for insert to authenticated
  with check (app.is_active_user() and app.can_contact_organisation(organisation_id));

create policy client_booklets_update_can_contact on public.client_booklets
  for update to authenticated
  using (app.is_active_user() and app.can_contact_organisation(organisation_id))
  with check (app.is_active_user() and app.can_contact_organisation(organisation_id));

create policy client_booklets_delete_admin on public.client_booklets
  for delete to authenticated
  using (app.is_active_user() and app.is_admin());
