-- Migration: version_client_booklets
-- Story: F086 (#350) Regenerate Client Booklet, on top of F085 (#349) Save
--   Generated Booklet (20260827000001_create_client_booklets.sql).
--
-- WHY THIS CHANGES F085'S OWN DESIGN, NOT A NEW TABLE:
--   F085's migration chose "one row per organisation, upserted on regenerate" —
--   its own header explains why: F085's ACs described a single current booklet,
--   and its ticket flagged versioning as an open question, not a requirement.
--   F086 answers that question: AC2 explicitly requires "the prior saved version
--   remains retrievable, so a bad regeneration isn't unrecoverable." An upsert
--   target cannot satisfy that — the prior text is gone the instant a
--   regeneration succeeds.
--
-- THE NEW SHAPE: append-only, exactly ENRICHMENT_RESULTS's own pattern.
--   Drops the organisation_id UNIQUE constraint and the update trigger/column —
--   a booklet row is now insert-only and immutable once written, never updated.
--   "The current booklet" is simply the most recent row for that organisation,
--   same as ENRICHMENT_RESULTS's own "latest row wins, ordered by enriched_at
--   desc" convention (20260804180000_create_org_children.sql). The route's
--   upsert becomes a plain insert; nothing UPDATEs this table anymore, so the
--   UPDATE policy and grant are removed rather than left unreachable.
--
-- SCHEMA CHANGE APPROVAL RECORD — DEVIATION, NOT YET MIRRORED (SOP §7):
--   Same flag as F085's migration: CLIENT_BOOKLETS is not yet in the Data Model
--   spreadsheet. This changes what needs adding there — an append-only history
--   table, not a single-row-per-organisation one — so the eventual spreadsheet
--   entry should reflect this shape, not F085's original one.
--   Change        | Alter CLIENT_BOOKLETS: drop organisation_id uniqueness and
--                 | updated_at/its trigger; add a (organisation_id, generated_at
--                 | desc) index for latest-row lookup; drop the now-unreachable
--                 | UPDATE policy.
--   Reason        | F086 AC2: a regeneration must not destroy the prior version.
--   Compatibility | F085 (#382) is unmerged at the time this is written — both
--                 | migrations land together, so no environment ever runs the
--                 | single-row shape with live writers.
--   Data migration| None.
--   Security      | RLS stays on; INSERT/SELECT/DELETE policies unchanged in
--                 | substance, UPDATE policy and grant removed (rows are now
--                 | immutable).
--   Documentation | Still not in the Data Model spreadsheet — flagged above.
--
-- Reversibility: paired rollback in ../rollback/20260828000000_version_client_booklets.down.sql
-- restores the unique constraint, the updated_at column/trigger, and the UPDATE
-- policy — but cannot undo any history a version-aware app has since written:
-- rolling back after real regenerations happened would silently pick an
-- arbitrary one of that organisation's rows to keep. Fine for a same-day
-- pre-merge revert; not safe once this has taken real traffic.

alter table public.client_booklets
  drop constraint client_booklets_organisation_id_key;

drop trigger client_booklets_set_updated_at on public.client_booklets;

alter table public.client_booklets
  drop column updated_at;

-- Matches enrichment_results_organisation_idx exactly: "the current row" is a
-- `where organisation_id = $1 order by generated_at desc limit 1` query, and this
-- index makes that an index-only scan instead of a sort over every version.
create index client_booklets_organisation_idx
  on public.client_booklets (organisation_id, generated_at desc);

drop policy client_booklets_update_can_contact on public.client_booklets;
revoke update on public.client_booklets from authenticated;

comment on table public.client_booklets is
  'Every generated booklet for a client (F085, versioned by F086) — append-only, '
  'never updated. "The current booklet" is the most recent row per organisation '
  '(order by generated_at desc), same convention as ENRICHMENT_RESULTS. Prior '
  'versions stay queryable so a bad regeneration is never unrecoverable (F086 AC2).';
comment on column public.client_booklets.generated_at is
  'When this version was generated by Gemini. Determines version order — there is '
  'no separate row-touch timestamp now that rows are immutable.';
