-- Migration: drop_charity_register_tables
-- Story: import criteria as data, not code — the register moves out of Postgres.
--
-- Drops CHARITY_REGISTER and CHARITY_REGISTER_RETURNS, which staged the whole
-- Charity Commission register inside the application database.
--
-- WHY THEY ARE GOING
--
-- Measured on staging, the two tables were 570MB — more than the entire Supabase
-- free tier — against 45MB for the actual application. They are a cache of a
-- file the regulator publishes publicly and republishes daily, so every byte of
-- them is regenerable in about twelve minutes. Sent emails and replies are not.
-- Spending the whole storage budget on the regenerable half, and squeezing the
-- irreplaceable half, is the wrong trade at any size.
--
-- The register now lives as a read-only SQLite file built by
-- .github/workflows/refresh-charity-register.yml and shipped inside the Vercel
-- deployment. It answers the same filter queries in under 200ms and costs the
-- database nothing. See docs/charity-register-import.md.
--
-- Nothing is lost. Organisations already imported from these tables live in
-- ORGANISATIONS and RAW_SOURCE_RECORDS and are untouched — they were copied out,
-- not linked back. IMPORT_FILTER_PRESETS stays: saved filter sets are the team's
-- own work rather than a copy of anything, and they are a few hundred bytes.
--
-- Schema change approval record (SOP §7):
--   Change        | Drop 2 tables: CHARITY_REGISTER, CHARITY_REGISTER_RETURNS.
--   Reason        | Superseded by a file shipped with the deployment. They cost
--                 | 570MB of a 500MB budget to hold public, regenerable data.
--   Compatibility | Nothing reads them: the import path now reads the file
--                 | (src/lib/charity-register/sqlite.ts), in the same commit.
--   Data migration| None needed — the file is built from the regulator's extracts,
--                 | not from these tables.
--   Security      | Removes a table holding contact details for 171,800
--                 | organisations from the database entirely.
--   Documentation | Data Model tabs "03 Raw Data"/"04 Entities" lose both tables;
--                 | run npm run export:data-model.
--   Approved by   | Bashir (Project Leader).
--
-- Reversibility: paired rollback in
-- ../rollback/20260915120000_drop_charity_register_tables.down.sql — but note it
-- restores empty tables. The data comes back by rebuilding, not by rolling back.

drop table if exists public.charity_register_returns;
drop table if exists public.charity_register;
